export const FALLBACK_DATABASE: Record<string, any[]> = {
  "aksi": [
    {
      id: "act-1",
      title: "The Dark Knight",
      year: 2008,
      rating: 9.0,
      votesCount: "2.8M ratings",
      genres: ["Action", "Crime", "Drama"],
      director: "Christopher Nolan",
      cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
      synopsis: "Ketika ancaman yang dikenal sebagai The Joker mengacaukan kota Gotham, Batman harus menerima salah satu ujian psikologis dan fisik terbesar untuk melawan ketidakadilan.",
      trendReason: "Peringkat #1 Film Aksi Terbaik sepanjang masa di IMDb dengan skor konsensus 94% dari 2,8 juta pemberi rating global.",
      popularityScore: 98,
      ratingPercentage: 94,
      bannerColor: "from-slate-800 to-slate-950"
    },
    {
      id: "act-2",
      title: "Mad Max: Fury Road",
      year: 2015,
      rating: 8.1,
      votesCount: "1.1M ratings",
      genres: ["Action", "Adventure", "Sci-Fi"],
      director: "George Miller",
      cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
      synopsis: "Di gurun pasir yang tandus, seorang wanita memberontak melawan penguasa tirani demi mencari tanah airnya, dibantu oleh sekelompok tahanan wanita dan seorang pengembara bernama Max.",
      trendReason: "Mengalami lonjakan pencarian +20% minggu ini karena rilisnya prekuel Furiosa, dipuji secara global untuk aksi praktis terbaik.",
      popularityScore: 92,
      ratingPercentage: 97,
      bannerColor: "from-amber-700 to-orange-950"
    },
    {
      id: "act-3",
      title: "Spider-Man: Across the Spider-Verse",
      year: 2023,
      rating: 8.6,
      votesCount: "350k ratings",
      genres: ["Action", "Animation", "Adventure"],
      director: "Joaquim Dos Santos",
      cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
      synopsis: "Miles Morales terlempar melintasi Multiverse, di mana ia bertemu dengan tim Spider-People yang bertugas melindungi keberadaannya. Namun saat pahlawan-pahlawan bertikai, Miles harus mendefinisikan ulang arti menjadi pahlawan.",
      trendReason: "Rating luar biasa tinggi dari penonton global, menjadikannya salah satu film animasi aksi dengan rating tertinggi dekade ini.",
      popularityScore: 95,
      ratingPercentage: 95,
      bannerColor: "from-pink-600 to-indigo-950"
    },
    {
      id: "act-4",
      title: "John Wick: Chapter 4",
      year: 2023,
      rating: 7.9,
      votesCount: "310k ratings",
      genres: ["Action", "Thriller"],
      director: "Chad Stahelski",
      cast: ["Keanu Reeves", "Laurence Fishburne", "George Georgiou"],
      synopsis: "John Wick menemukan jalan untuk mengalahkan High Table. Namun sebelum dia bisa mendapatkan kebebasannya, Wick harus berhadapan dengan musuh baru dengan aliansi kuat di seluruh dunia.",
      trendReason: "Aksi koreografi mutakhir yang ditonton lebih dari 150 juta jam di platform streaming global bulan lalu.",
      popularityScore: 89,
      ratingPercentage: 94,
      bannerColor: "from-red-900 to-zinc-950"
    },
    {
      id: "act-5",
      title: "Inception",
      year: 2010,
      rating: 8.8,
      votesCount: "2.5M ratings",
      genres: ["Action", "Sci-Fi", "Adventure"],
      director: "Christopher Nolan",
      cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
      synopsis: "Seorang pencuri yang mencuri rahasia perusahaan melalui penggunaan teknologi berbagi mimpi diberi tugas sebaliknya: menanamkan ide ke dalam pikiran seorang CEO.",
      trendReason: "Secara konsisten masuk dalam jajaran 5 besar film aksi fiksi ilmiah paling banyak didiskusikan di Letterboxd secara global.",
      popularityScore: 94,
      ratingPercentage: 91,
      bannerColor: "from-cyan-900 to-slate-950"
    },
    {
      id: "act-6",
      title: "Top Gun: Maverick",
      year: 2022,
      rating: 8.3,
      votesCount: "620k ratings",
      genres: ["Action", "Drama"],
      director: "Joseph Kosinski",
      cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
      synopsis: "Setelah lebih dari tiga puluh tahun mengabdi sebagai salah satu penerbang top Angkatan Laut, Pete Maverick Mitchell kembali melatih lulusan elit untuk misi berbahaya yang menuntut pengorbanan tertinggi.",
      trendReason: "Dicintai oleh kritikus dan penonton karena menghadirkan sensasi penerbangan jet tempur nyata tanpa CGI berlebih.",
      popularityScore: 93,
      ratingPercentage: 96,
      bannerColor: "from-sky-700 to-blue-950"
    },
    {
      id: "act-7",
      title: "Gladiator",
      year: 2000,
      rating: 8.5,
      votesCount: "1.5M ratings",
      genres: ["Action", "Adventure", "Drama"],
      director: "Ridley Scott",
      cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
      synopsis: "Seorang mantan jenderal Romawi bersiap membalas dendam terhadap kaisar korup yang membunuh keluarganya dan mengirimnya ke perbudakan gladiator.",
      trendReason: "Karya kolosal Ridley Scott yang memenangkan 5 Piala Oscar, termasuk Film Terbaik, dan terus menjadi acuan utama film aksi sejarah.",
      popularityScore: 91,
      ratingPercentage: 88,
      bannerColor: "from-amber-800 to-yellow-950"
    },
    {
      id: "act-8",
      title: "Kill Bill: Vol. 1",
      year: 2003,
      rating: 8.2,
      votesCount: "1.1M ratings",
      genres: ["Action", "Crime", "Thriller"],
      director: "Quentin Tarantino",
      cast: ["Uma Thurman", "Lucy Liu", "Vivica A. Fox"],
      synopsis: "Setelah terbangun dari koma selama empat tahun, seorang mantan pembunuh bayaran melancarkan aksi balas dendam tanpa ampun terhadap tim pembunuh yang mengkhianatinya.",
      trendReason: "Mahakarya aksi Quentin Tarantino bergaya sinematik martial arts klasik yang ikonik dan sangat berpengaruh dalam budaya populer.",
      popularityScore: 90,
      ratingPercentage: 85,
      bannerColor: "from-yellow-500 to-zinc-950"
    }
  ],
  "komedi": [
    {
      id: "com-1",
      title: "Everything Everywhere All at Once",
      year: 2022,
      rating: 8.5,
      votesCount: "480k ratings",
      genres: ["Comedy", "Action", "Sci-Fi"],
      director: "Daniel Kwan, Daniel Scheinert",
      cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
      synopsis: "Seorang imigran Tionghoa paruh baya terseret ke dalam petualangan luar biasa di mana ia sendiri yang dapat menyelamatkan dunia dengan menjelajahi alam semesta lain yang terhubung dengan kehidupan yang bisa ia jalani.",
      trendReason: "Pemenang 7 Piala Oscar yang memadukan komedi absurd dengan kehangatan keluarga, mempertahankan tren diskusi organik yang sangat tinggi.",
      popularityScore: 94,
      ratingPercentage: 93,
      bannerColor: "from-purple-600 to-rose-950"
    },
    {
      id: "com-2",
      title: "Knives Out",
      year: 2019,
      rating: 7.9,
      votesCount: "750k ratings",
      genres: ["Comedy", "Mystery", "Drama"],
      director: "Rian Johnson",
      cast: ["Daniel Craig", "Chris Evans", "Ana de Armas"],
      synopsis: "Seorang detektif menyelidiki kematian misterius seorang patriark keluarga yang eksentrik dan agresif.",
      trendReason: "Komedi misteri modern terpopuler yang mengumpulkan pujian global atas humor satir cerdas dan plot twist yang brilian.",
      popularityScore: 88,
      ratingPercentage: 97,
      bannerColor: "from-emerald-700 to-cyan-950"
    },
    {
      id: "com-3",
      title: "The Grand Budapest Hotel",
      year: 2014,
      rating: 8.1,
      votesCount: "850k ratings",
      genres: ["Comedy", "Drama"],
      director: "Wes Anderson",
      cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"],
      synopsis: "Seorang pramutamu di resor Eropa terkenal dituduh melakukan pembunuhan dan berteman dengan salah satu karyawannya untuk membuktikan bahwa dirinya tidak bersalah.",
      trendReason: "Estetika visual ikonik dengan humor bergaya quirky yang menjadi tren viral konstan di TikTok dan Instagram.",
      popularityScore: 86,
      ratingPercentage: 92,
      bannerColor: "from-pink-500 to-purple-950"
    },
    {
      id: "com-4",
      title: "Superbad",
      year: 2007,
      rating: 7.6,
      votesCount: "630k ratings",
      genres: ["Comedy"],
      director: "Greg Mottola",
      cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse"],
      synopsis: "Dua siswa sekolah menengah yang bergantung satu sama lain dipaksa untuk menghadapi kecemasan perpisahan setelah rencana mereka untuk mengadakan pesta berisi minuman keras menjadi kacau.",
      trendReason: "Diakui secara universal sebagai salah satu film komedi remaja terbaik abad ke-21 dengan kutipan-kutipan yang masih tren hingga hari ini.",
      popularityScore: 85,
      ratingPercentage: 88,
      bannerColor: "from-yellow-600 to-amber-950"
    },
    {
      id: "com-5",
      title: "Free Guy",
      year: 2021,
      rating: 7.1,
      votesCount: "420k ratings",
      genres: ["Comedy", "Action", "Sci-Fi"],
      director: "Shawn Levy",
      cast: ["Ryan Reynolds", "Jodie Comer", "Taika Waititi"],
      synopsis: "Seorang teller bank menyadari bahwa dia sebenarnya adalah karakter latar belakang dalam video game dunia terbuka yang brutal.",
      trendReason: "Sangat populer di kalangan penonton muda dan gamer, memperoleh tingkat kepuasan penonton 94% di Rotten Tomatoes.",
      popularityScore: 84,
      ratingPercentage: 80,
      bannerColor: "from-blue-500 to-sky-950"
    },
    {
      id: "com-6",
      title: "The Hangover",
      year: 2009,
      rating: 7.7,
      votesCount: "810k ratings",
      genres: ["Comedy"],
      director: "Todd Phillips",
      cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis"],
      synopsis: "Tiga sahabat terbangun dari pesta lajang di Las Vegas tanpa ingatan malam sebelumnya, dan mendapati pengantin pria telah hilang secara misterius.",
      trendReason: "Menjadi fenomena komedi dewasa tersukses sepanjang masa dengan lelucon liar yang tak terlupakan.",
      popularityScore: 89,
      ratingPercentage: 79,
      bannerColor: "from-orange-500 to-amber-950"
    },
    {
      id: "com-7",
      title: "Mean Girls",
      year: 2004,
      rating: 7.1,
      votesCount: "420k ratings",
      genres: ["Comedy"],
      director: "Mark Waters",
      cast: ["Lindsay Lohan", "Rachel McAdams", "Tina Fey"],
      synopsis: "Cady Heron, seorang gadis remaja yang sebelumnya bersekolah di rumah, harus berhadapan dengan taktik kejam kelompok siswi populer di sekolah barunya.",
      trendReason: "Komedi remaja legendaris yang dialog-dialognya masih sangat populer digunakan sebagai meme internet hingga saat ini.",
      popularityScore: 88,
      ratingPercentage: 84,
      bannerColor: "from-pink-600 to-purple-950"
    },
    {
      id: "com-8",
      title: "Shaun of the Dead",
      year: 2004,
      rating: 7.9,
      votesCount: "580k ratings",
      genres: ["Comedy", "Horror"],
      director: "Edgar Wright",
      cast: ["Simon Pegg", "Nick Frost", "Kate Ashfield"],
      synopsis: "Seorang pria biasa di London yang sedang dilanda patah hati tiba-tiba harus memimpin sekelompok sahabatnya bertahan hidup dari kiamat zombie yang mendadak.",
      trendReason: "Dikenal sebagai parody zombie terbaik yang cerdas, menggabungkan komedi Inggris yang jenaka dengan aksi horor yang menegangkan.",
      popularityScore: 87,
      ratingPercentage: 92,
      bannerColor: "from-lime-800 to-emerald-950"
    }
  ],
  "drama": [
    {
      id: "dra-1",
      title: "The Shawshank Redemption",
      year: 1994,
      rating: 9.3,
      votesCount: "2.9M ratings",
      genres: ["Drama"],
      director: "Frank Darabont",
      cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
      synopsis: "Di penjara Shawshank, bankir Andy Dufresne menjalin persahabatan selama bertahun-tahun dengan sesama narapidana, Red, menemukan jalan menuju penebusan melalui tindakan kesopanan umum.",
      trendReason: "Film peringkat #1 sepanjang masa di IMDb selama lebih dari 15 tahun, menjadikannya rujukan drama legendaris dunia.",
      popularityScore: 99,
      ratingPercentage: 98,
      bannerColor: "from-stone-700 to-neutral-950"
    },
    {
      id: "dra-2",
      title: "Oppenheimer",
      year: 2023,
      rating: 8.4,
      votesCount: "680k ratings",
      genres: ["Biography", "Drama", "History"],
      director: "Christopher Nolan",
      cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
      synopsis: "Kisah fisikawan Amerika J. Robert Oppenheimer yang memimpin Proyek Manhattan untuk mengembangkan bom atom pertama bagi kemanusiaan, mengubah dunia selamanya.",
      trendReason: "Menang besar di berbagai penghargaan global dan memicu fenomena budaya 'Barbenheimer' dengan pendapatan lebih dari $950 juta.",
      popularityScore: 97,
      ratingPercentage: 93,
      bannerColor: "from-amber-950 to-stone-900"
    },
    {
      id: "dra-3",
      title: "Forrest Gump",
      year: 1994,
      rating: 8.8,
      votesCount: "2.2M ratings",
      genres: ["Drama", "Romance"],
      director: "Robert Zemeckis",
      cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
      synopsis: "Kisah luar biasa tentang seorang pria ber-IQ rendah yang menyaksikan dan secara tidak sengaja memengaruhi beberapa peristiwa bersejarah penting di Amerika Serikat.",
      trendReason: "Kehangatan ceritanya menjadikannya film kenyamanan keluarga teratas dengan miliaran tayangan streaming secara akumulatif.",
      popularityScore: 93,
      ratingPercentage: 96,
      bannerColor: "from-blue-600 to-indigo-950"
    },
    {
      id: "dra-4",
      title: "Parasite",
      year: 2019,
      rating: 8.5,
      votesCount: "920k ratings",
      genres: ["Drama", "Thriller", "Comedy"],
      director: "Bong Joon Ho",
      cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
      synopsis: "Keluarga miskin menyusup ke dalam rumah tangga kaya dengan berpura-pura menjadi profesional berkualifikasi tinggi, memicu rangkaian kejadian tak terduga.",
      trendReason: "Film non-bahasa Inggris pertama yang memenangkan Best Picture di Oscar, dipuji sebagai mahakarya kritik sosial modern.",
      popularityScore: 95,
      ratingPercentage: 99,
      bannerColor: "from-emerald-800 to-zinc-950"
    },
    {
      id: "dra-5",
      title: "Interstellar",
      year: 2014,
      rating: 8.7,
      votesCount: "2.0M ratings",
      genres: ["Drama", "Sci-Fi", "Adventure"],
      director: "Christopher Nolan",
      cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
      synopsis: "Sekelompok penjelajah melakukan perjalanan melintasi lubang cacing di luar angkasa dalam upaya untuk memastikan kelangsungan hidup umat manusia di bumi yang sekarat.",
      trendReason: "Mempertahankan basis penggemar fanatik global dengan keindahan visual dan narasi emosional hubungan ayah-anak.",
      popularityScore: 96,
      ratingPercentage: 86,
      bannerColor: "from-indigo-900 to-black"
    },
    {
      id: "dra-6",
      title: "The Godfather",
      year: 1972,
      rating: 9.2,
      votesCount: "2.0M ratings",
      genres: ["Drama", "Crime"],
      director: "Francis Ford Coppola",
      cast: ["Marlon Brando", "Al Pacino", "James Caan"],
      synopsis: "Patriark penuaan dari dinasti kejahatan terorganisir mentransfer kontrol kerajaannya yang terselubung ke putranya yang enggan berurusan dengan dunia mafia.",
      trendReason: "Mahakarya sinematik terbesar sepanjang sejarah film dengan penulisan karakter dan arahan musik legendaris.",
      popularityScore: 98,
      ratingPercentage: 97,
      bannerColor: "from-amber-900 to-zinc-950"
    },
    {
      id: "dra-7",
      title: "Fight Club",
      year: 1999,
      rating: 8.8,
      votesCount: "2.3M ratings",
      genres: ["Drama"],
      director: "David Fincher",
      cast: ["Brad Pitt", "Edward Norton", "Meat Loaf"],
      synopsis: "Seorang pekerja kantoran yang mengidap insomnia kronis bertemu dengan pembuat sabun eksentrik bernama Tyler Durden dan mendirikan sebuah klub bertarung rahasia.",
      trendReason: "Kritik tajam terhadap konsumerisme modern dengan salah satu plot twist paling mengejutkan dalam sejarah film.",
      popularityScore: 94,
      ratingPercentage: 80,
      bannerColor: "from-teal-800 to-slate-950"
    },
    {
      id: "dra-8",
      title: "Pulp Fiction",
      year: 1994,
      rating: 8.9,
      votesCount: "2.2M ratings",
      genres: ["Drama", "Crime"],
      director: "Quentin Tarantino",
      cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
      synopsis: "Kehidupan dua pembunuh bayaran, seorang petinju, istri seorang gangster, dan sepasang perampok restoran saling bersinggungan dalam empat kisah kekerasan dan penebusan.",
      trendReason: "Gaya penceritaan non-linear Tarantino yang revolusioner dengan dialog-dialog satir yang legendaris.",
      popularityScore: 95,
      ratingPercentage: 92,
      bannerColor: "from-red-800 to-neutral-950"
    }
  ],
  "sci-fi": [
    {
      id: "scifi-1",
      title: "Dune: Part Two",
      year: 2024,
      rating: 8.6,
      votesCount: "410k ratings",
      genres: ["Sci-Fi", "Action", "Adventure"],
      director: "Denis Villeneuve",
      cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
      synopsis: "Paul Atreides bersatu dengan Chani dan Fremen saat membalas dendam terhadap para konspirator yang menghancurkan keluarganya, berusaha mencegah masa depan mengerikan yang hanya bisa ia ramalkan.",
      trendReason: "Film fiksi ilmiah terpanas saat ini, meraih rating 95% di Rotten Tomatoes dengan pujian visual luar biasa tingkat dunia.",
      popularityScore: 99,
      ratingPercentage: 95,
      bannerColor: "from-amber-600 to-amber-950"
    },
    {
      id: "scifi-2",
      title: "Interstellar",
      year: 2014,
      rating: 8.7,
      votesCount: "2.0M ratings",
      genres: ["Sci-Fi", "Adventure", "Drama"],
      director: "Christopher Nolan",
      cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
      synopsis: "Di masa depan ketika bumi tidak lagi layak huni, sekelompok astronot melakukan perjalanan melewati lubang cacing untuk mencari planet baru bagi peradaban manusia.",
      trendReason: "Skor musik legendaris Hans Zimmer dan akurasi teori sains menjadikannya tren konstan di kalangan komunitas akademis dan sinema.",
      popularityScore: 96,
      ratingPercentage: 86,
      bannerColor: "from-blue-900 to-black"
    },
    {
      id: "scifi-3",
      title: "Blade Runner 2049",
      year: 2017,
      rating: 8.0,
      votesCount: "630k ratings",
      genres: ["Sci-Fi", "Mystery", "Action"],
      director: "Denis Villeneuve",
      cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
      synopsis: "Seorang blade runner baru, polisi LAPD bernama K, menemukan rahasia lama yang terkubur yang berpotensi menjerumuskan apa yang tersisa dari masyarakat ke dalam kekacauan.",
      trendReason: "Mencapai status 'cult-classic' modern dengan estetika neon cyberpunk yang mendominasi tren desain futuristik.",
      popularityScore: 90,
      ratingPercentage: 88,
      bannerColor: "from-cyan-800 to-fuchsia-950"
    },
    {
      id: "scifi-4",
      title: "The Matrix",
      year: 1999,
      rating: 8.7,
      votesCount: "2.0M ratings",
      genres: ["Sci-Fi", "Action"],
      director: "Lana Wachowski, Lilly Wachowski",
      cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
      synopsis: "Seorang hacker komputer mempelajari sifat asli dari realitasnya dari para pemberontak misterius dan perannya dalam perang melawan penguasa sistem.",
      trendReason: "Film fiksi ilmiah revolusioner yang mendefinisikan ulang CGI aksi, tetap menjadi tontonan wajib referensi budaya teknologi pop.",
      popularityScore: 91,
      ratingPercentage: 96,
      bannerColor: "from-teal-800 to-zinc-950"
    },
    {
      id: "scifi-5",
      title: "Arrival",
      year: 2016,
      rating: 7.9,
      votesCount: "740k ratings",
      genres: ["Sci-Fi", "Drama", "Mystery"],
      director: "Denis Villeneuve",
      cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
      synopsis: "Seorang ahli bahasa dipanggil oleh militer untuk berkomunikasi dengan alien yang mendarat di bumi, mengungkap misteri yang menantang pemahaman kita tentang waktu.",
      trendReason: "Dikenal sebagai salah satu film tentang komunikasi alien paling cerdas dan mengharukan yang pernah diproduksi.",
      popularityScore: 87,
      ratingPercentage: 94,
      bannerColor: "from-sky-800 to-neutral-950"
    },
    {
      id: "scifi-6",
      title: "Star Wars: The Empire Strikes Back",
      year: 1980,
      rating: 8.7,
      votesCount: "1.3M ratings",
      genres: ["Sci-Fi", "Action", "Adventure"],
      director: "Irvin Kershner",
      cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
      synopsis: "Setelah Pemberontak diserang secara brutal oleh Kekaisaran di planet es Hoth, Luke Skywalker memulai pelatihan Jedi dengan Yoda, sementara teman-temannya dikejar oleh Darth Vader.",
      trendReason: "Secara luas dianggap sebagai sekuel terbaik dan film fiksi ilmiah luar angkasa terhebat sepanjang sejarah sinema.",
      popularityScore: 95,
      ratingPercentage: 97,
      bannerColor: "from-purple-800 to-indigo-950"
    },
    {
      id: "scifi-7",
      title: "The Prestige",
      year: 2006,
      rating: 8.5,
      votesCount: "1.4M ratings",
      genres: ["Sci-Fi", "Mystery", "Drama"],
      director: "Christopher Nolan",
      cast: ["Hugh Jackman", "Christian Bale", "Scarlett Johansson"],
      synopsis: "Setelah tragedi tragis di panggung, dua pesulap bersaing ketat di London abad ke-19, berkorban apa saja demi menciptakan trik sulap teleportasi terbaik yang melanggar hukum sains.",
      trendReason: "Ketegangan fiksi ilmiah psikologis Christopher Nolan yang memukau penonton dengan narasi persaingan obsesif.",
      popularityScore: 92,
      ratingPercentage: 92,
      bannerColor: "from-emerald-900 to-stone-950"
    },
    {
      id: "scifi-8",
      title: "Spider-Man: Into the Spider-Verse",
      year: 2018,
      rating: 8.4,
      votesCount: "630k ratings",
      genres: ["Sci-Fi", "Animation", "Action"],
      director: "Bob Persichetti",
      cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
      synopsis: "Remaja Miles Morales menjadi Spider-Man baru di alam semestanya, dan harus berkolaborasi dengan lima pahlawan laba-laba dari dimensi lain untuk menghentikan ancaman kolapsnya realitas.",
      trendReason: "Pemenang Oscar yang diakui atas inovasi visual animasi 3D tercanggih dengan kisah petualangan multiverse terbaik.",
      popularityScore: 94,
      ratingPercentage: 97,
      bannerColor: "from-rose-600 to-violet-950"
    }
  ],
  "horor": [
    {
      id: "hor-1",
      title: "Get Out",
      year: 2017,
      rating: 7.8,
      votesCount: "680k ratings",
      genres: ["Horror", "Mystery", "Thriller"],
      director: "Jordan Peele",
      cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
      synopsis: "Seorang pemuda kulit hitam mengunjungi keluarga pacar kulit putihnya untuk akhir pekan, di mana ia perlahan-lahan menyadari rahasia menyeramkan yang tersembunyi di balik keramahan mereka.",
      trendReason: "Sangat dipuji secara kritis dan sosial, memenangkan Oscar untuk Best Original Screenplay dan merevolusi horor psikologis modern.",
      popularityScore: 92,
      ratingPercentage: 98,
      bannerColor: "from-red-950 to-neutral-950"
    },
    {
      id: "hor-2",
      title: "Hereditary",
      year: 2018,
      rating: 7.3,
      votesCount: "390k ratings",
      genres: ["Horror", "Mystery", "Drama"],
      director: "Ari Aster",
      cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro"],
      synopsis: "Setelah kematian nenek mereka, sebuah keluarga yang berduka mulai diganggu oleh kejadian misterius dan tragis, mengungkap warisan gelap leluhur mereka.",
      trendReason: "Dianggap sebagai film paling menakutkan abad ini oleh banyak kritikus, dengan akting Toni Collette yang fenomenal.",
      popularityScore: 90,
      ratingPercentage: 90,
      bannerColor: "from-violet-950 to-stone-950"
    },
    {
      id: "hor-3",
      title: "A Quiet Place",
      year: 2018,
      rating: 7.5,
      votesCount: "580k ratings",
      genres: ["Horror", "Sci-Fi", "Drama"],
      director: "John Krasinski",
      cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds"],
      synopsis: "Sebuah keluarga berjuang bertahan hidup di dunia pasca-apokaliptik yang dihuni oleh makhluk buta berpendenaran tajam yang berburu murni berdasarkan suara.",
      trendReason: "Konsep unik yang menegangkan tanpa suara, meraih kesuksesan finansial besar dan melahirkan waralaba horor global populer.",
      popularityScore: 88,
      ratingPercentage: 96,
      bannerColor: "from-teal-950 to-slate-900"
    },
    {
      id: "hor-4",
      title: "Midsommar",
      year: 2019,
      rating: 7.1,
      votesCount: "410k ratings",
      genres: ["Horror", "Drama", "Mystery"],
      director: "Ari Aster",
      cast: ["Florence Pugh", "Jack Reynor", "William Jackson Harper"],
      synopsis: "Sepasang kekasih melakukan perjalanan ke festival musim panas Swedia yang tampak indah, namun liburan mereka berubah menjadi mimpi buruk sekte pagan di siang bolong.",
      trendReason: "Gaya 'folk horror' terang benderang yang memicu estetika pakaian bunga-bunga dan kontras menyeramkan yang viral di media sosial.",
      popularityScore: 89,
      ratingPercentage: 83,
      bannerColor: "from-amber-800 to-yellow-950"
    },
    {
      id: "hor-5",
      title: "The Conjuring",
      year: 2013,
      rating: 7.5,
      votesCount: "540k ratings",
      genres: ["Horror", "Mystery"],
      director: "James Wan",
      cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor"],
      synopsis: "Penyelidik paranormal Ed dan Lorraine Warren bekerja untuk membantu keluarga yang mengalami peristiwa mistis menakutkan di rumah pertanian Rhode Island mereka.",
      trendReason: "Film horor supranatural klasik modern yang meluncurkan waralaba sinematik horor tersukses secara finansial sepanjang sejarah.",
      popularityScore: 87,
      ratingPercentage: 86,
      bannerColor: "from-indigo-950 to-neutral-900"
    },
    {
      id: "hor-6",
      title: "The Shining",
      year: 1980,
      rating: 8.4,
      votesCount: "1.1M ratings",
      genres: ["Horror", "Drama"],
      director: "Stanley Kubrick",
      cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"],
      synopsis: "Sebuah keluarga menetap di sebuah hotel terpencil di pegunungan untuk musim dingin, di mana kehadiran spiritual yang jahat memengaruhi sang ayah menjadi kejam dan histeris.",
      trendReason: "Adaptasi novel Stephen King oleh Stanley Kubrick yang menjadi mahakarya horor psikologis legendaris dunia sinema.",
      popularityScore: 93,
      ratingPercentage: 85,
      bannerColor: "from-red-950 to-stone-950"
    },
    {
      id: "hor-7",
      title: "Psycho",
      year: 1960,
      rating: 8.5,
      votesCount: "710k ratings",
      genres: ["Horror", "Mystery", "Thriller"],
      director: "Alfred Hitchcock",
      cast: ["Anthony Perkins", "Janet Leigh", "Vera Miles"],
      synopsis: "Seorang sekretaris kabur setelah mencuri uang perusahaan, dan menginap di motel sunyi yang dikelola oleh seorang pemuda misterius di bawah kendali ibunya.",
      trendReason: "Film thriller/horor paling berpengaruh karya Alfred Hitchcock yang menetapkan standar emas sinematografi horor modern.",
      popularityScore: 91,
      ratingPercentage: 96,
      bannerColor: "from-zinc-900 to-neutral-950"
    },
    {
      id: "hor-8",
      title: "Alien",
      year: 1979,
      rating: 8.5,
      votesCount: "920k ratings",
      genres: ["Horror", "Sci-Fi"],
      director: "Ridley Scott",
      cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
      synopsis: "Awak pesawat luar angkasa komersial Nostromo menerima panggilan darurat dari planet asing, tak sengaja membawa parasit mematikan yang mulai memangsa kru satu per satu.",
      trendReason: "Perpaduan brilian fiksi ilmiah luar angkasa dengan teror claustrophobic yang memicu salah satu seri horor paling legendaris.",
      popularityScore: 92,
      ratingPercentage: 98,
      bannerColor: "from-emerald-950 to-black"
    }
  ],
  "romantis": [
    {
      id: "rom-1",
      title: "La La Land",
      year: 2016,
      rating: 8.0,
      votesCount: "660k ratings",
      genres: ["Comedy", "Drama", "Music", "Romance"],
      director: "Damien Chazelle",
      cast: ["Ryan Gosling", "Emma Stone", "Rosemarie DeWitt"],
      synopsis: "Seorang musisi jazz dan aktris yang bercita-cita tinggi jatuh cinta di Los Angeles, namun karir mereka yang menanjak mengancam merobek hubungan mereka.",
      trendReason: "Visual warna-warni yang luar biasa dengan lagu-lagu ikonik, menjadikannya salah satu film romantis modern yang paling dicantai secara global.",
      popularityScore: 94,
      ratingPercentage: 91,
      bannerColor: "from-fuchsia-600 to-purple-950"
    },
    {
      id: "rom-2",
      title: "About Time",
      year: 2013,
      rating: 7.8,
      votesCount: "380k ratings",
      genres: ["Drama", "Fantasy", "Romance"],
      director: "Richard Curtis",
      cast: ["Domhnall Gleeson", "Rachel McAdams", "Bill Nighy"],
      synopsis: "Pada usia 21 tahun, Tim menemukan bahwa pria di keluarganya dapat melakukan perjalanan waktu. Ia memutuskan untuk menggunakan kekuatannya untuk mendapatkan pacar.",
      trendReason: "Sangat direkomendasikan secara viral di media sosial sebagai film romantis paling mengharukan yang mengajarkan makna menghargai hari ini.",
      popularityScore: 91,
      ratingPercentage: 87,
      bannerColor: "from-rose-600 to-red-950"
    },
    {
      id: "rom-3",
      title: "Past Lives",
      year: 2023,
      rating: 7.9,
      votesCount: "120k ratings",
      genres: ["Drama", "Romance"],
      director: "Celine Song",
      cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
      synopsis: "Dua teman masa kecil yang terpisah secara mendalam bertemu kembali selama satu minggu yang menentukan di New York, menghadapi konsep takdir (In-Yun) dan cinta.",
      trendReason: "Karya romantis berperingkat kritis tertinggi tahun lalu, dipuji secara universal atas narasinya yang tenang, realistis, dan emosional.",
      popularityScore: 93,
      ratingPercentage: 96,
      bannerColor: "from-sky-700 to-indigo-950"
    },
    {
      id: "rom-4",
      title: "Pride & Prejudice",
      year: 2005,
      rating: 7.8,
      votesCount: "340k ratings",
      genres: ["Drama", "Romance"],
      director: "Joe Wright",
      cast: ["Keira Knightley", "Matthew Macfadyen", "Brenda Blethyn"],
      synopsis: "Elizabeth Bennet yang berjiwa bebas menghadapi ketegangan cinta, kesalahpahaman, kelas sosial, dan kebanggaan dalam hubungannya dengan Mr. Darcy yang kaya raya.",
      trendReason: "Adaptasi novel Jane Austen terbaik dengan sinematografi indah yang terus menjadi favorit nomor satu untuk kencan romantis santai.",
      popularityScore: 89,
      ratingPercentage: 88,
      bannerColor: "from-emerald-700 to-teal-950"
    },
    {
      id: "rom-5",
      title: "Before Sunrise",
      year: 1995,
      rating: 8.1,
      votesCount: "320k ratings",
      genres: ["Drama", "Romance"],
      director: "Richard Linklater",
      cast: ["Ethan Hawke", "Julie Delpy", "Andrea Eckert"],
      synopsis: "Seorang pemuda Amerika dan seorang wanita Prancis bertemu di kereta di Eropa dan menghabiskan satu malam romantis bersama berjalan-jalan di kota Wina.",
      trendReason: "Diakui sebagai trilogi romantis terbaik sepanjang masa, menawarkan percakapan mendalam yang sangat disukai para pecinta sinema.",
      popularityScore: 90,
      ratingPercentage: 100,
      bannerColor: "from-orange-600 to-amber-950"
    },
    {
      id: "rom-6",
      title: "Titanic",
      year: 1997,
      rating: 7.9,
      votesCount: "1.3M ratings",
      genres: ["Drama", "Romance"],
      director: "James Cameron",
      cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
      synopsis: "Anggota aristokrasi berusia tujuh belas tahun jatuh cinta dengan seorang seniman miskin namun baik hati di atas kapal mewah Titanic yang megah dan naas.",
      trendReason: "Salah satu film dengan pendapatan tertinggi sepanjang masa yang memenangkan 11 Piala Oscar dan mendefinisikan romansa epik abad ini.",
      popularityScore: 95,
      ratingPercentage: 88,
      bannerColor: "from-cyan-900 to-blue-950"
    },
    {
      id: "rom-7",
      title: "The Notebook",
      year: 2004,
      rating: 7.8,
      votesCount: "610k ratings",
      genres: ["Drama", "Romance"],
      director: "Nick Cassavetes",
      cast: ["Ryan Gosling", "Rachel McAdams", "Gena Rowlands"],
      synopsis: "Kisah cinta abadi antara seorang pemuda miskin dari penggergajian kayu dan seorang gadis kaya raya, diceritakan kembali dari buku catatan tua di masa senja mereka.",
      trendReason: "Drama romantis paling mengharukan dengan chemistry legendaris Ryan Gosling dan Rachel McAdams yang dicintai secara global.",
      popularityScore: 92,
      ratingPercentage: 85,
      bannerColor: "from-pink-800 to-rose-950"
    },
    {
      id: "rom-8",
      title: "500 Days of Summer",
      year: 2009,
      rating: 7.7,
      votesCount: "540k ratings",
      genres: ["Comedy", "Drama", "Romance"],
      director: "Marc Webb",
      cast: ["Joseph Gordon-Levitt", "Zooey Deschanel", "Geoffrey Arend"],
      synopsis: "Sebuah analisis acak, realistis, dan jujur tentang seorang pemuda penulis kartu ucapan yang jatuh cinta setengah mati pada gadis eksentrik bernama Summer.",
      trendReason: "Kisah cinta anti-mainstream yang realistis dan dipuji kritis karena membalikkan stereotip romantis klise Hollywood.",
      popularityScore: 91,
      ratingPercentage: 85,
      bannerColor: "from-sky-700 to-slate-900"
    }
  ]
};
